### PR TITLE
Validate paths based on what nginx will accept

### LINKED ISSUE #16: Regression in function of dispatcher relative to router
Router allowed access to all the Nginx options for location paths. For example:
`/foo` would match `/foo`, `/foo/bar`, `/foobar`
`/foo/` would match `/foo/bar` but not `/foo`
`=/foo` would match `/foo` only. It would not match `/foo/bar` or `/foobar`
`~bar$` would match `/foobar` and `/foo/bar`, but not `/foo`

I think we need to restore the flexibility we took away. We have made dispatcher Edge-specific, which I don't think we want. We should also rename 'basePath' to something else at the same time — basePath does not accurately capture the concept. 'location' is one obvious choice. 'pathPattern' might also make sense.

### PR DESCRIPTION
**Pull request by AdamMagaluk**
Fixes #16 

Ensures path are a valid regex syntax as that is what nginx validates on.

### CODE REVIEW

File: router/pods_test.go [hunk 1]
```diff
@@ -800,30 +800,26 @@ func TestGetHealthCheckFromPodPort(t *testing.T) {
 
 // TestValidatePath tests the internal function to validate a proper path used in annotations
 func TestValidatePath(t *testing.T) {
-	testNoPrefix := "test"
-	testPathFail := "/test/%2a/%"
-	testPathPass := "/test/%2a/aa/a"
-	testPathPassProperEncoding := "/test/par%2ate/aa/a"
-	testPathFailInvalidEncoding := "/test/hello%zzworld/aa/a"
```
Comment (whitlockjc) [inline router/pods_test.go]: Did you mean to remove these test cases?

Comment (AdamMagaluk) [inline router/pods_test.go]: Yes, as those are still valid nginx paths, though probably not useful. Nginx will take anything that is a valid pcre regex syntax. Therefor our test cases is basically just anything that fails to compile a regex in go.

Comment (whitlockjc) [inline router/pods_test.go]: But does it benefit the user to be able to specify a path that is invalid outside of nginx?  Doing so might end up with the path being inaccessible even if nginx will serve it.  The purpose of these checks were to tell the user they've defined an invalid URI path and I still think they would be useful checks on top of the nginx check.

Comment (AdamMagaluk) [inline router/pods_test.go]: I'm not sure how we would validate otherwise though, since nginx supports a regex as path match we cannot really verify that it's a valid url path because it may be a regex.

Comment (whitlockjc) [inline router/pods_test.go]: I'm just saying that just because nginx won't barf on an invalid URI path doesn't mean it's valid and shouldn't trigger an error.  If nginx serves an invalid path that cannot be reached, what good is it?

Comment (AdamMagaluk) [inline router/pods_test.go]: What would you consider an invalid path regex?

Comment (whitlockjc) [inline router/pods_test.go]: We had code at one point that validated URI path segments.

Comment (AdamMagaluk) [inline router/pods_test.go]: Sure, but the some users (Martin) want to use a regex for matching a path. How would a URI validator make any sense of that? The input to nginx and our path is not a URI it's a path match pattern (or at least this PR makes it so).

Comment (whitlockjc) [inline router/pods_test.go]: Ah, I get what you're saying now.  :)  If the user provides a regex, you cannot use the URI validation regex to validate that.  We're on the same page...although I wonder if there's a better way.  What about different values?  `path` vs. `pathRegex`?  Just thinking aloud.

Comment (AdamMagaluk) [inline router/pods_test.go]: So that was actually something Martin brought up when i first talk to him about it. He proposed we change `path` to something more descriptive like `pathPattern` or something i forgot what he proposed.

Though  i don't think two separate values is very useful, it's still the same thing your providing just in one case your providing the simplest proper URI format.

Comment (AdamMagaluk) [inline router/pods_test.go]: He proposed `location`. See his use case: https://github.com/30x/dispatcher/issues/16

Comment (whitlockjc) [inline router/pods_test.go]: I think it's fine as-is.  What we were doing was a _nice-to-have_ anyways.  I do think two separate properties that could each be validated separately might work but I don't care either way.
